# Generated by Django 5.0 on 2026-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_jobposting_skills_jobposting_visa_sponsorship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
